apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: testing
  namespace: default
data:
  k8s.v1.cni.cncf.io/networks: {{`'[{"name":"vlan99","namespace":"default","ips":[`}}{{ .Values.ip }}{{`]}]'`}}